import React, { useState } from 'react';
import { FileText, Calendar, Clock, Eye, Printer, EyeOff, X, ChevronLeft, ChevronRight } from 'lucide-react';
import toast from 'react-hot-toast';
import { doc, updateDoc } from 'firebase/firestore';
import { db } from '../../../fireBaseConfig';

export default function GeneratedPapers({
    questionPapers,
    setActiveTab,
    setGeneratedPaper,
    setShowPreview,
    previewPaper,
    showPreview,
    generatedPaper,
    formatDateTime
}) {
    const [currentPage, setCurrentPage] = useState(1);
    const itemsPerPage = 5;

    // Filter logic
    const filteredPapers = questionPapers.filter(paper => paper.status === "generated");

    // Pagination logic
    const totalPages = Math.ceil(filteredPapers.length / itemsPerPage);
    const indexOfLastItem = currentPage * itemsPerPage;
    const indexOfFirstItem = indexOfLastItem - itemsPerPage;
    const currentPapers = filteredPapers.slice(indexOfFirstItem, indexOfLastItem);

    // Reset to page 1 if papers change significantly (optional, but good practice)
    React.useEffect(() => {
        if (currentPage > totalPages && totalPages > 0) {
            setCurrentPage(1);
        }
    }, [filteredPapers.length]);


    return (
        <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
            <div className="flex items-center justify-between mb-6">
                <div>
                    <h2 className="text-2xl font-bold text-gray-900">Generated Question Papers</h2>
                    <p className="text-sm text-gray-500 mt-1">{filteredPapers.length} papers generated</p>
                </div>
                <button onClick={() => setActiveTab("generate")} className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 flex items-center gap-2">
                    <FileText className="w-4 h-4" /> Generate New Paper
                </button>
            </div>

            <div className="space-y-4">
                {currentPapers.map(paper => (
                    <div key={paper.id} className="border border-gray-200 rounded-lg p-4 hover:shadow-sm transition">
                        <div className="flex items-start justify-between">
                            <div className="flex-1">
                                <div className="flex items-center gap-2 mb-2">
                                    <h3 className="font-semibold text-gray-900">{paper.title}</h3>
                                    <span className={`px-2 py-1 rounded text-xs font-medium ${paper.status === 'generated' ? 'bg-green-100 text-green-800' :
                                        paper.status === 'scheduled' ? 'bg-yellow-100 text-yellow-800' :
                                            'bg-gray-100 text-gray-800'
                                        }`}>
                                        {paper.status?.toUpperCase() || 'DRAFT'}
                                    </span>
                                    {paper.isAutoGenerated && (
                                        <span className="px-2 py-1 rounded text-xs font-medium bg-purple-100 text-purple-800">
                                            Auto-Generated
                                        </span>
                                    )}
                                </div>
                                <p className="text-sm text-gray-600">{paper.subjectCode} - {paper.subjectName}</p>
                                <div className="flex flex-wrap items-center gap-4 mt-2 text-xs text-gray-500">
                                    <span className="flex items-center gap-1">
                                        <Calendar size={12} />
                                        {paper.examDate || "Date not set"}
                                    </span>
                                    <span>•</span>
                                    <span className="flex items-center gap-1">
                                        <Clock size={12} />
                                        {paper.examTime || "Time not set"}
                                    </span>
                                    <span>•</span>
                                    <span>{paper.duration || 3} hours</span>
                                    <span>•</span>
                                    <span>{paper.totalQuestions || paper.questions?.length || 0} questions</span>
                                    <span>•</span>
                                    <span>{paper.totalMarks || 0} marks</span>
                                </div>
                                {paper.marksDistribution && (
                                    <div className="mt-2 text-xs text-gray-600">
                                        <span className="mr-3">1-mark: {paper.marksDistribution.oneMark?.count || 0}</span>
                                        <span className="mr-3">3-mark: {paper.marksDistribution.threeMark?.count || 0}</span>
                                        <span>5-mark: {paper.marksDistribution.fiveMark?.count || 0}</span>
                                    </div>
                                )}
                                {paper.generatedAt && (
                                    <div className="mt-2 text-xs text-gray-400">
                                        Generated: {paper.generatedAt.toDate ? paper.generatedAt.toDate().toLocaleString() : "Recently"}
                                    </div>
                                )}
                            </div>
                            <div className="flex items-center gap-2">
                                <button onClick={() => {
                                    setGeneratedPaper(paper);
                                    setShowPreview(true);
                                }} className="px-3 py-1 text-sm text-blue-600 hover:bg-blue-50 border border-blue-200 rounded-lg flex items-center gap-1">
                                    <Eye className="w-3 h-3" /> Preview
                                </button>
                                <button onClick={() => {
                                    if (paper.questions && paper.questions.length > 0) {
                                        setGeneratedPaper(paper);
                                        // Use a timeout to ensure state update before print
                                        setTimeout(() => previewPaper(paper), 0);
                                    } else {
                                        toast.error("No questions available to print");
                                    }
                                }} className="px-3 py-1 text-sm text-gray-600 hover:bg-gray-50 border border-gray-200 rounded-lg flex items-center gap-1">
                                    <Printer className="w-3 h-3" /> Print
                                </button>
                                <button onClick={async () => {
                                    try {
                                        const paperRef = doc(db, "questionPapers", paper.id);
                                        await updateDoc(paperRef, {
                                            visible: !paper.visible
                                        });
                                        toast.success(`Paper ${paper.visible ? 'hidden' : 'made visible'} for staff`);
                                    } catch (error) {
                                        toast.error("Error toggling visibility");
                                    }
                                }} className={`px-3 py-1 text-sm rounded-lg flex items-center gap-1 ${paper.visible
                                    ? 'text-green-600 hover:bg-green-50 border border-green-200'
                                    : 'text-gray-600 hover:bg-gray-50 border border-gray-200'
                                    }`}>
                                    {paper.visible ? (
                                        <>
                                            <Eye className="w-3 h-3" /> Visible
                                        </>
                                    ) : (
                                        <>
                                            <EyeOff className="w-3 h-3" /> Hidden
                                        </>
                                    )}
                                </button>
                            </div>
                        </div>

                        {paper.questions && paper.questions.length > 0 && (
                            <div className="mt-3 pt-3 border-t border-gray-100">
                                <div className="flex items-center gap-4">
                                    <div className="text-sm">
                                        <span className="font-medium text-gray-700">Units covered: </span>
                                        <span className="text-gray-600">
                                            {paper.unitsCovered ? paper.unitsCovered.join(', ') :
                                                Array.from(new Set(paper.questions.map(q => q.unit))).join(', ')}
                                        </span>
                                    </div>
                                    <div className="text-sm">
                                        <span className="font-medium text-gray-700">Question types: </span>
                                        <span className="text-gray-600">
                                            {Array.from(new Set(paper.questions.map(q => q.type || 'Standard'))).join(', ')}
                                        </span>
                                    </div>
                                </div>
                            </div>
                        )}
                    </div>
                ))}

                {filteredPapers.length === 0 && (
                    <div className="text-center py-12 text-gray-500">
                        <FileText className="w-12 h-12 mx-auto text-gray-300 mb-3" />
                        <p className="text-lg font-medium">No generated papers yet</p>
                        <p className="text-sm mt-1">Generate your first question paper</p>
                        <button onClick={() => setActiveTab("generate")} className="mt-4 px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700">
                            Generate Paper
                        </button>
                    </div>
                )}
            </div>

            {/* Pagination Controls */}
            {totalPages > 1 && (
                <div className="flex items-center justify-between mt-6 pt-4 border-t border-gray-100">
                    <p className="text-sm text-gray-500">
                        Showing {(currentPage - 1) * itemsPerPage + 1} to {Math.min(currentPage * itemsPerPage, filteredPapers.length)} of {filteredPapers.length} papers
                    </p>
                    <div className="flex gap-2">
                        <button
                            onClick={() => setCurrentPage(prev => Math.max(1, prev - 1))}
                            disabled={currentPage === 1}
                            className="p-2 border border-gray-300 rounded-lg hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed"
                        >
                            <ChevronLeft className="w-4 h-4" />
                        </button>
                        <button
                            onClick={() => setCurrentPage(prev => Math.min(totalPages, prev + 1))}
                            disabled={currentPage === totalPages}
                            className="p-2 border border-gray-300 rounded-lg hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed"
                        >
                            <ChevronRight className="w-4 h-4" />
                        </button>
                    </div>
                </div>
            )}

            {/* PAPER PREVIEW MODAL */}
            {showPreview && generatedPaper && (
                <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
                    <div className="bg-white rounded-xl w-full max-w-4xl max-h-[90vh] overflow-y-auto">
                        <div className="sticky top-0 bg-white border-b border-gray-200 p-4 flex items-center justify-between">
                            <h3 className="text-lg font-semibold">{generatedPaper.title}</h3>
                            <div className="flex items-center gap-2">
                                <button onClick={() => previewPaper(generatedPaper)} className="px-3 py-1 bg-blue-600 text-white rounded-lg hover:bg-blue-700 flex items-center gap-1">
                                    <Printer className="w-4 h-4" /> Print/PDF
                                </button>
                                <button onClick={() => setShowPreview(false)} className="text-gray-400 hover:text-gray-600">
                                    <X className="w-5 h-5" />
                                </button>
                            </div>
                        </div>

                        <div className="p-6">
                            {/* Paper Header */}
                            <div className="text-center mb-8 border-b-2 border-gray-300 pb-6">
                                <h1 className="text-3xl font-bold text-gray-900 mb-2">{generatedPaper.title}</h1>
                                <h2 className="text-xl text-gray-700 mb-4">{generatedPaper.subjectCode} - {generatedPaper.subjectName}</h2>

                                <div className="flex flex-wrap justify-center gap-6 mt-4 text-sm text-gray-600">
                                    <div className="text-center">
                                        <p className="font-semibold">Date</p>
                                        <p>{generatedPaper.examDate || new Date().toLocaleDateString()}</p>
                                    </div>
                                    <div className="text-center">
                                        <p className="font-semibold">Time</p>
                                        <p>{generatedPaper.examTime || "09:30"} AM</p>
                                    </div>
                                    <div className="text-center">
                                        <p className="font-semibold">Duration</p>
                                        <p>{generatedPaper.duration || 3} Hours</p>
                                    </div>
                                    <div className="text-center">
                                        <p className="font-semibold">Total Marks</p>
                                        <p>{generatedPaper.totalMarks}</p>
                                    </div>
                                </div>
                            </div>

                            {/* Mark Distribution Summary */}
                            {generatedPaper.marksDistribution && (
                                <div className="mb-6 p-4 bg-blue-50 rounded-lg">
                                    <h3 className="font-semibold text-gray-900 mb-2">Mark Distribution</h3>
                                    <div className="grid grid-cols-3 gap-4 text-center">
                                        <div>
                                            <p className="text-sm text-gray-600">1-Mark Questions</p>
                                            <p className="text-lg font-semibold text-gray-900">{generatedPaper.marksDistribution.oneMark?.count || 0}</p>
                                            <p className="text-xs text-gray-500">{generatedPaper.marksDistribution.oneMark?.totalMarks || 0} marks</p>
                                        </div>
                                        <div>
                                            <p className="text-sm text-gray-600">3-Mark Questions</p>
                                            <p className="text-lg font-semibold text-gray-900">{generatedPaper.marksDistribution.threeMark?.count || 0}</p>
                                            <p className="text-xs text-gray-500">{generatedPaper.marksDistribution.threeMark?.totalMarks || 0} marks</p>
                                        </div>
                                        <div>
                                            <p className="text-sm text-gray-600">5-Mark Questions</p>
                                            <p className="text-lg font-semibold text-gray-900">{generatedPaper.marksDistribution.fiveMark?.count || 0}</p>
                                            <p className="text-xs text-gray-500">{generatedPaper.marksDistribution.fiveMark?.totalMarks || 0} marks</p>
                                        </div>
                                    </div>
                                </div>
                            )}

                            {/* Instructions */}
                            <div className="mb-8 p-4 bg-gray-50 rounded-lg">
                                <h3 className="font-semibold text-gray-900 mb-2">INSTRUCTIONS TO CANDIDATES</h3>
                                <ul className="list-disc pl-5 space-y-1 text-sm text-gray-700">
                                    <li>Answer ALL questions.</li>
                                    <li>Each question carries marks as indicated.</li>
                                    <li>Write answers in the answer booklet provided.</li>
                                    <li>Diagrams should be drawn wherever necessary.</li>
                                    <li>All questions are compulsory.</li>
                                    <li>Read the questions carefully before answering.</li>
                                </ul>
                            </div>

                            {/* Questions */}
                            <div className="mb-8">
                                <h3 className="text-2xl font-bold text-gray-900 mb-6 text-center">QUESTIONS</h3>

                                {generatedPaper.questions && generatedPaper.questions.map((question, index) => (
                                    <div key={question.id || index} className="mb-6 p-4 border border-gray-200 rounded-lg">
                                        <div className="flex justify-between items-start mb-3">
                                            <div className="flex items-center gap-3">
                                                <span className="font-bold text-lg">Q{index + 1}.</span>
                                                <span className={`text-sm px-3 py-1 rounded-full ${question.marks === 1 ? 'bg-blue-100 text-blue-800' :
                                                    question.marks === 3 ? 'bg-green-100 text-green-800' :
                                                        'bg-purple-100 text-purple-800'
                                                    }`}>
                                                    {question.marks || 0} Mark{question.marks !== 1 ? 's' : ''}
                                                </span>
                                                <span className="text-sm px-3 py-1 rounded-full bg-gray-100 text-gray-800">
                                                    Unit {question.unit}
                                                </span>
                                                {question.type && (
                                                    <span className="text-sm px-3 py-1 rounded-full bg-purple-100 text-purple-800">
                                                        {question.type}
                                                    </span>
                                                )}
                                                {question.level && (
                                                    <span className={`text-sm px-3 py-1 rounded-full ${question.level.toLowerCase() === 'hard' ? 'bg-red-100 text-red-800' :
                                                        question.level.toLowerCase() === 'medium' ? 'bg-yellow-100 text-yellow-800' :
                                                            'bg-green-100 text-green-800'
                                                        }`}>
                                                        {question.level}
                                                    </span>
                                                )}
                                            </div>
                                        </div>

                                        <p className="text-gray-800 mb-4">{question.question}</p>

                                        {question.options && question.options.length > 0 && (
                                            <div className="ml-6 space-y-2">
                                                {question.options.map((option, optIndex) => (
                                                    <div key={optIndex} className="flex items-center">
                                                        <span className="mr-2 font-medium">{String.fromCharCode(65 + optIndex)}.</span>
                                                        <span>{option}</span>
                                                    </div>
                                                ))}
                                            </div>
                                        )}
                                    </div>
                                ))}
                            </div>

                            {/* Footer */}
                            <div className="text-center mt-12 pt-6 border-t border-gray-300">
                                <p className="text-lg font-bold text-gray-900">*** END OF QUESTION PAPER ***</p>
                                <p className="text-sm text-gray-600 mt-2">Good Luck!</p>
                            </div>
                        </div>

                        <div className="sticky bottom-0 bg-white border-t border-gray-200 p-4 flex justify-center gap-4">
                            <button onClick={() => previewPaper(generatedPaper)} className="px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 flex items-center gap-2">
                                <Printer className="w-4 h-4" /> Print Paper
                            </button>
                            <button onClick={() => setShowPreview(false)} className="px-6 py-2 border border-gray-300 rounded-lg hover:bg-gray-50">
                                Close Preview
                            </button>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
}
