import React, { useState } from 'react';
import { Plus, CheckCircle, Clock, ChevronLeft, ChevronRight, Edit2, Calendar, Timer, FileText } from 'lucide-react';
import EditPaperModal from '../../components/EditPaperModal';
import { doc, updateDoc, serverTimestamp } from 'firebase/firestore';
import { db } from '../../../fireBaseConfig';
import toast from 'react-hot-toast';

export default function ScheduledPapers({
    scheduledPapers,
    setActiveTab
}) {
    const [currentPage, setCurrentPage] = useState(1);
    const [editingPaper, setEditingPaper] = useState(null);
    const itemsPerPage = 8;

    // Filter Logic
    const filteredPapers = scheduledPapers;

    // Pagination Logic
    const totalPages = Math.ceil(filteredPapers.length / itemsPerPage);
    const displayedPapers = filteredPapers.slice(
        (currentPage - 1) * itemsPerPage,
        currentPage * itemsPerPage
    );

    const handleUpdatePaper = async (paperId, updatedData) => {
        try {
            const paperRef = doc(db, "questionPapers", paperId);
            await updateDoc(paperRef, {
                ...updatedData,
                updatedAt: serverTimestamp()
            });

            toast.success("Paper updated successfully");
            setEditingPaper(null);
        } catch (error) {
            console.error("Error updating paper:", error);
            toast.error("Error updating paper details");
        }
    };

    return (
        <div className="bg-white/80 backdrop-blur-xl rounded-2xl shadow-lg border border-white/50 animate-fade-in overflow-hidden">
            <div className="p-6 border-b border-gray-100 flex flex-col md:flex-row md:items-center justify-between gap-4">
                <div>
                    <h2 className="text-xl font-bold text-gray-900 flex items-center gap-2">
                        <Timer className="w-6 h-6 text-amber-600" /> Scheduled Generation
                    </h2>
                    <p className="text-sm text-gray-500 mt-1">Manage automated question paper generation schedules</p>
                </div>
                <button
                    onClick={() => setActiveTab("generate")}
                    className="px-4 py-2 bg-gradient-to-r from-amber-500 to-orange-600 text-white rounded-xl hover:shadow-lg hover:shadow-amber-500/30 transition-all flex items-center gap-2 font-medium"
                >
                    <Plus className="w-4 h-4" /> Schedule New
                </button>
            </div>

            <div className="overflow-x-auto">
                <table className="w-full text-left border-collapse">
                    <thead>
                        <tr className="bg-gray-50/50 border-b border-gray-100 text-xs uppercase tracking-wider text-gray-500 font-semibold">
                            <th className="px-6 py-4">Paper Details</th>
                            <th className="px-6 py-4">Subject</th>
                            <th className="px-6 py-4">Scheduled For</th>
                            <th className="px-6 py-4">Exam Details</th>
                            <th className="px-6 py-4 text-right">Actions</th>
                        </tr>
                    </thead>
                    <tbody className="divide-y divide-gray-50">
                        {displayedPapers.map(paper => (
                            <tr key={paper.id} className="group hover:bg-amber-50/30 transition-colors">
                                <td className="px-6 py-4">
                                    <div>
                                        <div className="font-semibold text-gray-900 flex items-center gap-2">
                                            {paper.title}
                                            {paper.isAutoGenerated && (
                                                <span className="px-1.5 py-0.5 rounded text-[10px] font-bold bg-purple-100 text-purple-700 border border-purple-200 uppercase tracking-wide">
                                                    Auto
                                                </span>
                                            )}
                                        </div>
                                        <div className="text-xs text-gray-500 mt-0.5 flex items-center gap-1">
                                            <span className="w-1.5 h-1.5 rounded-full bg-amber-500 animate-pulse"></span>
                                            Pending Execution
                                        </div>
                                    </div>
                                </td>
                                <td className="px-6 py-4">
                                    <div className="text-sm">
                                        <p className="font-medium text-gray-700">{paper.subjectName}</p>
                                        <p className="text-xs text-gray-400 font-mono">{paper.subjectCode}</p>
                                    </div>
                                </td>
                                <td className="px-6 py-4">
                                    <div className="flex flex-col text-sm text-gray-600">
                                        <span className="flex items-center gap-1.5">
                                            <Calendar className="w-3.5 h-3.5 text-gray-400" />
                                            {paper.generationDate}
                                        </span>
                                        <span className="flex items-center gap-1.5 text-xs text-gray-400 mt-0.5">
                                            <Clock className="w-3 h-3" />
                                            {paper.generationTime}
                                        </span>
                                    </div>
                                </td>
                                <td className="px-6 py-4">
                                    <div className="text-xs text-gray-500 space-y-1">
                                        <span className="block">Date: <span className="font-medium text-gray-700">{paper.examDate}</span></span>
                                        <span className="block">Duration: <span className="font-medium text-gray-700">{paper.duration} Hrs</span></span>
                                    </div>
                                </td>
                                <td className="px-6 py-4 text-right">
                                    <button
                                        onClick={() => setEditingPaper(paper)}
                                        className="p-2 text-gray-400 hover:text-blue-600 hover:bg-blue-50 rounded-lg transition-colors"
                                        title="Edit Parameters"
                                    >
                                        <Edit2 className="w-4 h-4" />
                                    </button>
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>

                {scheduledPapers.length === 0 && (
                    <div className="text-center py-16">
                        <div className="w-16 h-16 bg-amber-50 rounded-full flex items-center justify-center mx-auto mb-4 border border-amber-100">
                            <Clock className="w-8 h-8 text-amber-400" />
                        </div>
                        <h3 className="text-lg font-medium text-gray-900">No papers scheduled</h3>
                        <p className="text-gray-500 mt-1">Schedule a new paper generation to get started</p>
                    </div>
                )}
            </div>

            {/* Pagination Controls */}
            {totalPages > 1 && (
                <div className="flex items-center justify-between px-6 py-4 border-t border-gray-100 bg-gray-50/30">
                    <p className="text-sm text-gray-500">
                        Page <span className="font-medium text-gray-900">{currentPage}</span> of <span className="font-medium text-gray-900">{totalPages}</span>
                    </p>
                    <div className="flex gap-2">
                        <button
                            onClick={() => setCurrentPage(prev => Math.max(1, prev - 1))}
                            disabled={currentPage === 1}
                            className="p-2 bg-white border border-gray-200 rounded-lg hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed transition-colors shadow-sm"
                        >
                            <ChevronLeft className="w-4 h-4 text-gray-600" />
                        </button>
                        <button
                            onClick={() => setCurrentPage(prev => Math.min(totalPages, prev + 1))}
                            disabled={currentPage === totalPages}
                            className="p-2 bg-white border border-gray-200 rounded-lg hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed transition-colors shadow-sm"
                        >
                            <ChevronRight className="w-4 h-4 text-gray-600" />
                        </button>
                    </div>
                </div>
            )}

            {/* Edit Modal */}
            {editingPaper && (
                <EditPaperModal
                    paper={editingPaper}
                    onClose={() => setEditingPaper(null)}
                    onSave={handleUpdatePaper}
                />
            )}
        </div>
    );
}
