import React from 'react';
import { Plus, CheckCircle, Clock } from 'lucide-react';

export default function ScheduledPapers({
    scheduledPapers,
    setActiveTab
}) {
    return (
        <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
            <div className="flex items-center justify-between mb-6">
                <h2 className="text-2xl font-bold text-gray-900">Scheduled Paper Generation</h2>
                <button onClick={() => setActiveTab("generate")} className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 flex items-center gap-2">
                    <Plus className="w-4 h-4" /> Schedule New Paper
                </button>
            </div>

            <div className="space-y-4">
                {scheduledPapers.map(paper => (
                    <div key={paper.id} className="border border-gray-200 rounded-lg p-4 hover:shadow-sm transition">
                        <div className="flex items-center justify-between">
                            <div className="flex-1">
                                <div className="flex items-center gap-2 mb-2">
                                    <h3 className="font-semibold text-gray-900">{paper.title}</h3>
                                    <span className="px-2 py-1 rounded text-xs font-medium bg-yellow-100 text-yellow-800">
                                        Scheduled
                                    </span>
                                    {paper.isAutoGenerated && (
                                        <span className="px-2 py-1 rounded text-xs font-medium bg-purple-100 text-purple-800">
                                            Auto-Generate
                                        </span>
                                    )}
                                </div>
                                <div className="grid grid-cols-2 gap-4 text-sm text-gray-600">
                                    <div>
                                        <span className="font-medium">Subject:</span> {paper.subjectCode} - {paper.subjectName}
                                    </div>
                                    <div>
                                        <span className="font-medium">Generation Time:</span> {paper.generationDate} at {paper.generationTime}
                                    </div>
                                    <div>
                                        <span className="font-medium">Exam Date:</span> {paper.examDate}
                                    </div>
                                    <div>
                                        <span className="font-medium">Duration:</span> {paper.duration} Hours
                                    </div>
                                </div>
                            </div>
                            <div className="flex items-center gap-2 text-gray-500">
                                <Clock className="w-5 h-5" />
                                <span className="text-sm">Pending</span>
                            </div>
                        </div>
                    </div>
                ))}

                {scheduledPapers.length === 0 && (
                    <div className="text-center py-12 text-gray-500">
                        <CheckCircle className="w-12 h-12 mx-auto text-gray-300 mb-3" />
                        <p className="text-lg font-medium">No scheduled papers</p>
                        <p className="text-sm mt-1">Schedule a paper generation to see it here</p>
                    </div>
                )}
            </div>
        </div>
    );
}
